version: '3.3'

services:
  main:
    build: ./
    command: bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 -- bin/rails server -p 3000 -b 0.0.0.0
    restart: always
    environment:
        RAILS_ENV: "${RAILS_ENV}"
    volumes:
        - "./:/app"
    ports:
        - "3001:3000"
        - "1234:1234"
    stdin_open: true
    tty: true